remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-them
markdown: kramdown
show_downloads: false
title: Iranian Businesses Data Reports
navigation:
  Product Books: https://t.me/productbooks
  Product Inbox: https://t.me/productinbox
